/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EditorField: typeof import('./src/components/EditorField.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    GeneralBtn: typeof import('./src/components/GeneralBtn.vue')['default']
    HeadTitle: typeof import('./src/components/HeadTitle.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    ProgItem: typeof import('./src/components/ProgItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerField: typeof import('./src/components/ServerField.vue')['default']
    ServerItem: typeof import('./src/components/ServerItem.vue')['default']
    TabItem: typeof import('./src/components/TabItem.vue')['default']
    TheConsole: typeof import('./src/components/TheConsole.vue')['default']
  }
}
