/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Console: typeof import('./src/components/Console.vue')['default']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NIcon: typeof import('naive-ui')['NIcon']
    NPopover: typeof import('naive-ui')['NPopover']
    ProgItem: typeof import('./src/components/ProgItem.vue')['default']
    ProgList: typeof import('./src/components/ProgList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerItem: typeof import('./src/components/ServerItem.vue')['default']
    ServerOp: typeof import('./src/components/ServerOp.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
    TabItem: typeof import('./src/components/TabItem.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
    Upload: typeof import('./src/components/Upload.vue')['default']
  }
}
