/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EditorField: typeof import('./src/components/EditorField.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    GeneralBtn: typeof import('./src/components/GeneralBtn.vue')['default']
    HeadTitle: typeof import('./src/components/HeadTitle.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    ProgItem: typeof import('./src/components/ProgItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerField: typeof import('./src/components/ServerField.vue')['default']
    ServerItem: typeof import('./src/components/ServerItem.vue')['default']
    TabItem: typeof import('./src/components/TabItem.vue')['default']
    TheConsole: typeof import('./src/components/TheConsole.vue')['default']
  }
}

// For TSX support
declare global {
  const EditorField: typeof import('./src/components/EditorField.vue')['default']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElPopover: typeof import('element-plus/es')['ElPopover']
  const FileUpload: typeof import('./src/components/FileUpload.vue')['default']
  const GeneralBtn: typeof import('./src/components/GeneralBtn.vue')['default']
  const HeadTitle: typeof import('./src/components/HeadTitle.vue')['default']
  const MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
  const ProgItem: typeof import('./src/components/ProgItem.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ServerField: typeof import('./src/components/ServerField.vue')['default']
  const ServerItem: typeof import('./src/components/ServerItem.vue')['default']
  const TabItem: typeof import('./src/components/TabItem.vue')['default']
  const TheConsole: typeof import('./src/components/TheConsole.vue')['default']
}