/* tslint:disable */
/* eslint-disable */
/**
 * ecli API
 * RESTFul APIs provided by ecli-server
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GetTaskLogRequest
 */
export interface GetTaskLogRequest {
    /**
     * The program ID
     * @type {number}
     * @memberof GetTaskLogRequest
     */
    id: number;
    /**
     * Only fetch logs after this cursor (included). If not provided, return logs stored with minimum cursor
     * @type {number}
     * @memberof GetTaskLogRequest
     */
    log_cursor?: number;
    /**
     * Fetch at most such number of logs. If not provided, use a default value that server specified
     * @type {number}
     * @memberof GetTaskLogRequest
     */
    maximum_count?: number;
}
