/* tslint:disable */
/* eslint-disable */
/**
 * ecli API
 * RESTFul APIs provided by ecli-server
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LogType } from './log-type';
/**
 * 
 * @export
 * @interface LogLog
 */
export interface LogLog {
    /**
     * 
     * @type {string}
     * @memberof LogLog
     */
    log: string;
    /**
     * 
     * @type {number}
     * @memberof LogLog
     */
    timestamp: number;
    /**
     * 
     * @type {LogType}
     * @memberof LogLog
     */
    log_type: LogType;
}
