/* tslint:disable */
/* eslint-disable */
/**
 * ecli API
 * RESTFul APIs provided by ecli-server
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TaskStatus } from './task-status';
/**
 * 
 * @export
 * @interface TaskListResponseTasks
 */
export interface TaskListResponseTasks {
    /**
     * 
     * @type {TaskStatus}
     * @memberof TaskListResponseTasks
     */
    status: TaskStatus;
    /**
     * The ID of the task
     * @type {number}
     * @memberof TaskListResponseTasks
     */
    id: number;
    /**
     * The name of the task
     * @type {string}
     * @memberof TaskListResponseTasks
     */
    name: string;
}
