/* tslint:disable */
/* eslint-disable */
/**
 * ecli API
 * RESTFul APIs provided by ecli-server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface GeneralError
 */
export interface GeneralError {
    /**
     * description of the unexpected situation
     * @type {string}
     * @memberof GeneralError
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface GetTaskLogRequest
 */
export interface GetTaskLogRequest {
    /**
     * The program ID
     * @type {number}
     * @memberof GetTaskLogRequest
     */
    'id': number;
    /**
     * Only fetch logs after this cursor (included). If not provided, return logs stored with minimum cursor
     * @type {number}
     * @memberof GetTaskLogRequest
     */
    'log_cursor'?: number;
    /**
     * Fetch at most such number of logs. If not provided, use a default value that server specified
     * @type {number}
     * @memberof GetTaskLogRequest
     */
    'maximum_count'?: number;
}
/**
 * 
 * @export
 * @interface GetTaskLogResponseInner
 */
export interface GetTaskLogResponseInner {
    /**
     * 
     * @type {number}
     * @memberof GetTaskLogResponseInner
     */
    'cursor': number;
    /**
     * 
     * @type {GetTaskLogResponseInnerLog}
     * @memberof GetTaskLogResponseInner
     */
    'log': GetTaskLogResponseInnerLog;
}
/**
 * 
 * @export
 * @interface GetTaskLogResponseInnerLog
 */
export interface GetTaskLogResponseInnerLog {
    /**
     * 
     * @type {string}
     * @memberof GetTaskLogResponseInnerLog
     */
    'log': string;
    /**
     * 
     * @type {number}
     * @memberof GetTaskLogResponseInnerLog
     */
    'timestamp': number;
    /**
     * 
     * @type {LogType}
     * @memberof GetTaskLogResponseInnerLog
     */
    'log_type': LogType;
}


/**
 * 
 * @export
 * @enum {string}
 */

export const LogType = {
    Stderr: 'stderr',
    Stdout: 'stdout',
    Plain: 'plain'
} as const;

export type LogType = typeof LogType[keyof typeof LogType];


/**
 * 
 * @export
 * @enum {string}
 */

export const ProgramType = {
    Wasm: 'wasm',
    Json: 'json',
    Tar: 'tar'
} as const;

export type ProgramType = typeof ProgramType[keyof typeof ProgramType];


/**
 * 
 * @export
 * @interface SimpleIdRequest
 */
export interface SimpleIdRequest {
    /**
     * 
     * @type {number}
     * @memberof SimpleIdRequest
     */
    'id': number;
}
/**
 * 
 * @export
 * @interface StartTask200Response
 */
export interface StartTask200Response {
    /**
     * 
     * @type {number}
     * @memberof StartTask200Response
     */
    'id': number;
    /**
     * 
     * @type {TaskListResponse}
     * @memberof StartTask200Response
     */
    'task_list': TaskListResponse;
}
/**
 * 
 * @export
 * @interface StartTaskRequest
 */
export interface StartTaskRequest {
    /**
     * Base64-encoded program data
     * @type {string}
     * @memberof StartTaskRequest
     */
    'program_data_buf': string;
    /**
     * 
     * @type {ProgramType}
     * @memberof StartTaskRequest
     */
    'program_type': ProgramType;
    /**
     * The name of the program. If not provided, will generate a random one
     * @type {string}
     * @memberof StartTaskRequest
     */
    'program_name'?: string;
    /**
     * Btf archive path in the server.
     * @type {string}
     * @memberof StartTaskRequest
     */
    'btf_archive_path'?: string;
    /**
     * Command line arguments to the eBPF program
     * @type {Array<string>}
     * @memberof StartTaskRequest
     */
    'extra_args'?: Array<string>;
    /**
     * Whether to let the bpf-loader program dumps json. Only works for json & tar program
     * @type {boolean}
     * @memberof StartTaskRequest
     */
    'export_json'?: boolean;
}


/**
 * 
 * @export
 * @interface TaskListResponse
 */
export interface TaskListResponse {
    /**
     * 
     * @type {Array<TaskListResponseTasksInner>}
     * @memberof TaskListResponse
     */
    'tasks': Array<TaskListResponseTasksInner>;
}
/**
 * 
 * @export
 * @interface TaskListResponseTasksInner
 */
export interface TaskListResponseTasksInner {
    /**
     * 
     * @type {TaskStatus}
     * @memberof TaskListResponseTasksInner
     */
    'status': TaskStatus;
    /**
     * The ID of the task
     * @type {number}
     * @memberof TaskListResponseTasksInner
     */
    'id': number;
    /**
     * The name of the task
     * @type {string}
     * @memberof TaskListResponseTasksInner
     */
    'name': string;
}


/**
 * The status of the task
 * @export
 * @enum {string}
 */

export const TaskStatus = {
    Running: 'running',
    Paused: 'paused'
} as const;

export type TaskStatus = typeof TaskStatus[keyof typeof TaskStatus];



/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get list of running tasks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTaskList: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/task`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * get log from server
         * @summary get log
         * @param {GetTaskLogRequest} getTaskLogRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTaskLogByID: async (getTaskLogRequest: GetTaskLogRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'getTaskLogRequest' is not null or undefined
            assertParamExists('getTaskLogByID', 'getTaskLogRequest', getTaskLogRequest)
            const localVarPath = `/log`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(getTaskLogRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Pause a task by id
         * @param {SimpleIdRequest} simpleIdRequest Task id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pauseTaskByID: async (simpleIdRequest: SimpleIdRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'simpleIdRequest' is not null or undefined
            assertParamExists('pauseTaskByID', 'simpleIdRequest', simpleIdRequest)
            const localVarPath = `/pause`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(simpleIdRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Resume a task by id
         * @param {SimpleIdRequest} simpleIdRequest Task id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resumeTaskByID: async (simpleIdRequest: SimpleIdRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'simpleIdRequest' is not null or undefined
            assertParamExists('resumeTaskByID', 'simpleIdRequest', simpleIdRequest)
            const localVarPath = `/resume`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(simpleIdRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Start a new task
         * @param {StartTaskRequest} startTaskRequest Task data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startTask: async (startTaskRequest: StartTaskRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'startTaskRequest' is not null or undefined
            assertParamExists('startTask', 'startTaskRequest', startTaskRequest)
            const localVarPath = `/task`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(startTaskRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Stop a task by id
         * @param {SimpleIdRequest} simpleIdRequest Task id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        stopTaskByID: async (simpleIdRequest: SimpleIdRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'simpleIdRequest' is not null or undefined
            assertParamExists('stopTaskByID', 'simpleIdRequest', simpleIdRequest)
            const localVarPath = `/stop`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(simpleIdRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get list of running tasks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTaskList(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTaskList(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * get log from server
         * @summary get log
         * @param {GetTaskLogRequest} getTaskLogRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTaskLogByID(getTaskLogRequest: GetTaskLogRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetTaskLogResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTaskLogByID(getTaskLogRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Pause a task by id
         * @param {SimpleIdRequest} simpleIdRequest Task id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pauseTaskByID(simpleIdRequest: SimpleIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskStatus>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pauseTaskByID(simpleIdRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Resume a task by id
         * @param {SimpleIdRequest} simpleIdRequest Task id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resumeTaskByID(simpleIdRequest: SimpleIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskStatus>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resumeTaskByID(simpleIdRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Start a new task
         * @param {StartTaskRequest} startTaskRequest Task data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async startTask(startTaskRequest: StartTaskRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StartTask200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.startTask(startTaskRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Stop a task by id
         * @param {SimpleIdRequest} simpleIdRequest Task id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async stopTaskByID(simpleIdRequest: SimpleIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.stopTaskByID(simpleIdRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Get list of running tasks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTaskList(options?: any): AxiosPromise<TaskListResponse> {
            return localVarFp.getTaskList(options).then((request) => request(axios, basePath));
        },
        /**
         * get log from server
         * @summary get log
         * @param {GetTaskLogRequest} getTaskLogRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTaskLogByID(getTaskLogRequest: GetTaskLogRequest, options?: any): AxiosPromise<Array<GetTaskLogResponseInner>> {
            return localVarFp.getTaskLogByID(getTaskLogRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Pause a task by id
         * @param {SimpleIdRequest} simpleIdRequest Task id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pauseTaskByID(simpleIdRequest: SimpleIdRequest, options?: any): AxiosPromise<TaskStatus> {
            return localVarFp.pauseTaskByID(simpleIdRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Resume a task by id
         * @param {SimpleIdRequest} simpleIdRequest Task id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resumeTaskByID(simpleIdRequest: SimpleIdRequest, options?: any): AxiosPromise<TaskStatus> {
            return localVarFp.resumeTaskByID(simpleIdRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Start a new task
         * @param {StartTaskRequest} startTaskRequest Task data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startTask(startTaskRequest: StartTaskRequest, options?: any): AxiosPromise<StartTask200Response> {
            return localVarFp.startTask(startTaskRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Stop a task by id
         * @param {SimpleIdRequest} simpleIdRequest Task id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        stopTaskByID(simpleIdRequest: SimpleIdRequest, options?: any): AxiosPromise<object> {
            return localVarFp.stopTaskByID(simpleIdRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Get list of running tasks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getTaskList(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getTaskList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * get log from server
     * @summary get log
     * @param {GetTaskLogRequest} getTaskLogRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getTaskLogByID(getTaskLogRequest: GetTaskLogRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getTaskLogByID(getTaskLogRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Pause a task by id
     * @param {SimpleIdRequest} simpleIdRequest Task id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public pauseTaskByID(simpleIdRequest: SimpleIdRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).pauseTaskByID(simpleIdRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Resume a task by id
     * @param {SimpleIdRequest} simpleIdRequest Task id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public resumeTaskByID(simpleIdRequest: SimpleIdRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).resumeTaskByID(simpleIdRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Start a new task
     * @param {StartTaskRequest} startTaskRequest Task data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public startTask(startTaskRequest: StartTaskRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).startTask(startTaskRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Stop a task by id
     * @param {SimpleIdRequest} simpleIdRequest Task id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public stopTaskByID(simpleIdRequest: SimpleIdRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).stopTaskByID(simpleIdRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



